# Generated by Django 2.1.5 on 2025-03-27 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='DefaultUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='TBC', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Player Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('sport', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sheets', to='Match_Ready.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sheets', to='Match_Ready.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('defaultuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Match_Ready.DefaultUser')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_profile', to='Match_Ready.Team')),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
            bases=('Match_Ready.defaultuser',),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('defaultuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Match_Ready.DefaultUser')),
                ('favourite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='Match_Ready.Team')),
            ],
            bases=('Match_Ready.defaultuser',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('defaultuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Match_Ready.DefaultUser')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='Match_Ready.Team')),
            ],
            bases=('Match_Ready.defaultuser',),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='team_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_availabilities', to='Match_Ready.TeamSheet'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='Match_Ready.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='Match_Ready.Team'),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaultuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Match_Ready.Team'),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Match_Ready.Player'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Match_Ready.Coach'),
        ),
        migrations.AlterUniqueTogether(
            name='playeravailability',
            unique_together={('team_sheet', 'player')},
        ),
    ]
