# Generated by Django 2.2.28 on 2025-03-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
