# Generated by Django 2.2.28 on 2025-03-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0002_auto_20250321_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
