# Generated by Django 2.2.28 on 2025-03-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0002_auto_20250325_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='favourite_team',
            new_name='team',
        ),
    ]
