# Generated by Django 2.2.28 on 2025-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0003_auto_20250326_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
