# Generated by Django 2.2.28 on 2025-03-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0005_auto_20250326_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
