# Generated by Django 2.2.28 on 2025-03-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0006_auto_20250326_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
