# Generated by Django 2.2.28 on 2025-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match_Ready', '0007_remove_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attendies',
            field=models.ManyToManyField(blank=True, default=0, related_name='attending_matches', to='Match_Ready.Fan'),
        ),
    ]
