# Generated by Django 2.2.28 on 2025-03-27 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Match_Ready', '0010_auto_20250327_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attendees_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
